/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biograph.gui;

/**
 *
 * @author Usuario
 */
public class VentanaBio extends javax.swing.JFrame {
    // Creamos una instancia global de tu lógica
    biograph.logica.GrafoProteico miGrafo = new biograph.logica.GrafoProteico(2000); 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBio.class.getName());

    /**
     * Creates new form VentanaBio
     */
    public VentanaBio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        txtEntrada = new javax.swing.JTextField();
        btnCluster = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaResultados = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        btnHub = new javax.swing.JButton();
        btnRuta = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVisualizarRed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                ANÁLISIS DE REDES PROTEICAS");

        btnCargar.setText("Cargar CSV");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnCluster.setText("Buscar Cluster");
        btnCluster.addActionListener(this::btnClusterActionPerformed);

        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        jScrollPane2.setViewportView(txtAreaResultados);

        btnEliminar.setText("Eliminar Proteína");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnHub.setText("Identificar HUB");
        btnHub.addActionListener(this::btnHubActionPerformed);

        btnRuta.setText("Ruta más Corta");
        btnRuta.addActionListener(this::btnRutaActionPerformed);

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnVisualizarRed.setText("Ver Grafo");
        btnVisualizarRed.addActionListener(this::btnVisualizarRedActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCluster, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisualizarRed)
                            .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCluster)
                            .addComponent(btnCargar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVisualizarRed)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnRuta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHub)
                            .addComponent(btnGuardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // 1. Creamos el selector de archivos (Esto elimina el error de JFileChooser)
        javax.swing.JFileChooser explorador = new javax.swing.JFileChooser();
    
        // 2. Abrimos la ventana y guardamos el resultado en 'seleccion'
        int seleccion = explorador.showOpenDialog(this);
    
        // 3. Si el usuario eligió un archivo y le dio a "Abrir"
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = explorador.getSelectedFile();
            String rutaAbsoluta = archivoSeleccionado.getAbsolutePath();
        
            // 4. Cargamos los datos usando tu variable global
            miGrafo.cargarDesdeCSV(rutaAbsoluta); 
        
            // 5. Mostramos los resultados en el área de texto
            txtAreaResultados.setText(">>> Cargando archivo: " + archivoSeleccionado.getName() + "...\n");
            txtAreaResultados.append("Estado: ¡Carga Exitosa!\n");
            txtAreaResultados.append("Proteínas encontradas: " + miGrafo.getCantidad() + "\n");
            txtAreaResultados.append("------------------------------------------\n");
            txtAreaResultados.append(miGrafo.obtenerAnalisisHub());
        
            javax.swing.JOptionPane.showMessageDialog(this, "¡Grafo cargado exitosamente!");
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnClusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClusterActionPerformed
        String nombre = txtEntrada.getText().trim();
        if (!nombre.isEmpty()) {
            // Usamos tu método BFS
            String resultado = miGrafo.obtenerCluster(nombre);
            txtAreaResultados.append("\n\n" + resultado);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe el nombre de una proteína (Ej: P1)");
        }  
    }//GEN-LAST:event_btnClusterActionPerformed

    private void btnHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubActionPerformed
        txtAreaResultados.append("\n\n" + miGrafo.obtenerAnalisisHub());
    }//GEN-LAST:event_btnHubActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombre = txtEntrada.getText().trim();
        if (!nombre.isEmpty()) {
            miGrafo.eliminarProteina(nombre);
            txtAreaResultados.setText("Simulación de fármaco: Proteína '" + nombre + "' eliminada del sistema.");
        } else {
            txtAreaResultados.setText("Por favor, ingrese un nombre en el cuadro central.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        miGrafo.guardarEnCSV("maestro (2).csv"); 
    txtAreaResultados.append("\n>>> Repositorio CSV actualizado exitosamente.");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        String entrada = txtEntrada.getText().trim();
        if (entrada.contains(",")) {
            String[] partes = entrada.split(",");
            String origen = partes[0].trim();
            String destino = partes[1].trim();
        
            String resultado = miGrafo.obtenerRutaMasCorta(origen, destino);
            txtAreaResultados.append("\n\n" + resultado);
        } else {
            txtAreaResultados.append("\n[Error] Para ruta use formato: Origen,Destino (Ej: P1,P5)");
        }
    }//GEN-LAST:event_btnRutaActionPerformed

    private void btnVisualizarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarRedActionPerformed
        if (miGrafo != null && miGrafo.getCantidad() > 0) {
            miGrafo.mostrarRedVisual();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe cargar el CSV primero.");
    }
    }//GEN-LAST:event_btnVisualizarRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaBio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCluster;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHub;
    private javax.swing.JButton btnRuta;
    private javax.swing.JButton btnVisualizarRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaResultados;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
